name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      # Main profile information
      - name: Generate profile metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          user: kemisto17
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, repositories, metadata
          config_timezone: Asia/Kolkata
          config_display: regular


      # Isometric contribution calendar
      - name: Generate contribution calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalendar.svg
          user: kemisto17
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Kolkata


      # Coding habits
      - name: Generate coding habits
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.habits.svg
          user: kemisto17
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 6
          config_timezone: Asia/Kolkata


      # Languages
      - name: Generate language statistics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.languages.svg
          user: kemisto17
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_threshold: 0%
          config_timezone: Asia/Kolkata
      
      # GitHub Skyline
      - name: Generate GitHub Skyline
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.skyline.svg
          user: kemisto17
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2026
          plugin_skyline_frames: 60
          plugin_skyline_quality: 1
          config_timezone: Asia/Kolkata
